export const mockUserData = {
  ratings: [
    {
      id: 1,
      itemName: "The Daily Grind",
      category: "Coffee Shop",
      rating: 4.5,
      date: new Date("2025-01-15"),
      caption: "Great coffee and atmosphere!",
    },
    {
      id: 2,
      itemName: "Inception",
      category: "Movie",
      rating: 5,
      date: new Date("2025-01-14"),
      caption: "Mind-bending masterpiece",
    },
    {
      id: 3,
      itemName: "The Cozy Corner",
      category: "Restaurant",
      rating: 4.2,
      date: new Date("2025-01-13"),
      caption: "Perfect for date nights",
    },
    {
      id: 4,
      itemName: "Stanford University",
      category: "College",
      rating: 4.8,
      date: new Date("2025-01-12"),
      caption: "Excellent academics and campus",
    },
    {
      id: 5,
      itemName: "Blue Bottle Coffee",
      category: "Coffee Shop",
      rating: 4.0,
      date: new Date("2025-01-11"),
      caption: "Good but overpriced",
    },
    {
      id: 6,
      itemName: "Dune: Part Two",
      category: "Movie",
      rating: 4.7,
      date: new Date("2025-01-10"),
      caption: "Visually stunning sequel",
    },
    {
      id: 7,
      itemName: "Local Bistro",
      category: "Restaurant",
      rating: 3.8,
      date: new Date("2025-01-09"),
      caption: "Decent food, slow service",
    },
    {
      id: 8,
      itemName: "UC Berkeley",
      category: "College",
      rating: 4.5,
      date: new Date("2025-01-08"),
      caption: "Great research opportunities",
    },
  ],
  favorites: [
    { id: 1, itemName: "The Daily Grind", category: "Coffee Shop", dateAdded: new Date("2025-01-15") },
    { id: 2, itemName: "Inception", category: "Movie", dateAdded: new Date("2025-01-14") },
    { id: 3, itemName: "The Cozy Corner", category: "Restaurant", dateAdded: new Date("2025-01-13") },
    { id: 4, itemName: "Stanford University", category: "College", dateAdded: new Date("2025-01-12") },
    { id: 5, itemName: "Blue Bottle Coffee", category: "Coffee Shop", dateAdded: new Date("2025-01-10") },
    { id: 6, itemName: "Dune: Part Two", category: "Movie", dateAdded: new Date("2025-01-09") },
    { id: 7, itemName: "Local Bistro", category: "Restaurant", dateAdded: new Date("2025-01-08") },
    { id: 8, itemName: "Tartine Bakery", category: "Bakery", dateAdded: new Date("2025-01-07") },
    { id: 9, itemName: "The Matrix", category: "Movie", dateAdded: new Date("2025-01-06") },
    { id: 10, itemName: "Philz Coffee", category: "Coffee Shop", dateAdded: new Date("2025-01-05") },
    { id: 11, itemName: "MIT", category: "College", dateAdded: new Date("2025-01-04") },
    { id: 12, itemName: "Nopa Restaurant", category: "Restaurant", dateAdded: new Date("2025-01-03") },
    { id: 13, itemName: "Four Barrel Coffee", category: "Coffee Shop", dateAdded: new Date("2025-01-02") },
    { id: 14, itemName: "Oppenheimer", category: "Movie", dateAdded: new Date("2025-01-01") },
    { id: 15, itemName: "Harvard University", category: "College", dateAdded: new Date("2024-12-30") },
  ],
  lists: [
    { id: 1, name: "Best Coffee Shops in SF", itemCount: 8, dateCreated: new Date("2025-01-10"), isPrivate: false },
    { id: 2, name: "Must-Watch Movies 2024", itemCount: 12, dateCreated: new Date("2025-01-05"), isPrivate: false },
    { id: 3, name: "Top Universities", itemCount: 5, dateCreated: new Date("2024-12-28"), isPrivate: true },
    { id: 4, name: "Hidden Restaurant Gems", itemCount: 7, dateCreated: new Date("2024-12-20"), isPrivate: false },
    { id: 5, name: "Weekend Brunch Spots", itemCount: 6, dateCreated: new Date("2024-12-15"), isPrivate: true },
  ],
  badges: [
    { id: 1, name: "First Rating", description: "Posted your first rating", dateEarned: new Date("2024-12-01") },
    { id: 2, name: "Coffee Connoisseur", description: "Rated 10 coffee shops", dateEarned: new Date("2024-12-15") },
    { id: 3, name: "Movie Buff", description: "Rated 20 movies", dateEarned: new Date("2025-01-01") },
    { id: 4, name: "List Creator", description: "Created 5 custom lists", dateEarned: new Date("2025-01-05") },
    { id: 5, name: "Social Butterfly", description: "Got 50 likes on reviews", dateEarned: new Date("2025-01-08") },
    { id: 6, name: "Streak Master", description: "7-day rating streak", dateEarned: new Date("2025-01-12") },
    {
      id: 7,
      name: "Explorer",
      description: "Rated items in 5 different categories",
      dateEarned: new Date("2025-01-14"),
    },
  ],
}
